// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAmfIKb0xUyTJUTxQN-rile-Oy_pR4FA',
    appId: '1:188888034601:web:c677d3cf1db1a929255b38',
    messagingSenderId: '188888034601',
    projectId: 'iiithack',
    authDomain: 'iiithack.firebaseapp.com',
    storageBucket: 'iiithack.appspot.com',
    measurementId: 'G-Z49PBEW8SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnP5RR10BL52tdLnNjnIgOVuaRKr64iYE',
    appId: '1:188888034601:android:9be2b3a03850e03e255b38',
    messagingSenderId: '188888034601',
    projectId: 'iiithack',
    storageBucket: 'iiithack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzv7_Hw1N2227oh8KwvDCZ2spov0vd4Q',
    appId: '1:188888034601:ios:20d5c3215db32318255b38',
    messagingSenderId: '188888034601',
    projectId: 'iiithack',
    storageBucket: 'iiithack.appspot.com',
    iosBundleId: 'com.example.kassiDating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzv7_Hw1N2227oh8KwvDCZ2spov0vd4Q',
    appId: '1:188888034601:ios:c953053e24480c1e255b38',
    messagingSenderId: '188888034601',
    projectId: 'iiithack',
    storageBucket: 'iiithack.appspot.com',
    iosBundleId: 'com.example.kassiDating.RunnerTests',
  );
}
